<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/2/20 0020
 * Time: 14:43
 */

namespace mall;


class Controller_Car extends Controller_BaseController
{

    public function before()
    {
        parent::before(); // TODO: Change the autogenerated stub
    }

    /**
     * 获取汽车列表
     */
    public function get_index()
    {

    }

    /**
     * 获取某一辆汽车
     */
    public function get_item()
    {

    }

    /**
     * 创建一辆汽车
     */
    public function post_index()
    {

    }

    /**
     * 修改一辆汽车
     */
    public function put_index()
    {

    }

    /**
     * 更新一辆汽车的某些属性
     */
    public function patch_index()
    {
    }

    /**
     * 删除一辆汽车
     */
    public function delete_index()
    {

    }

    /**
     * 获取指定品牌下的车辆
     */
    public function get_brand(){}

    /**
     * 获取车辆款式
     */
    public function get_style(){}

    /**
     * 获取车辆类型
     */
    public function get_category(){}

    /**
     * 搜索车辆
     */
    public function get_search(){}

}