<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/2/20 0020
 * Time: 14:43
 */

namespace mall;


class Controller_Category extends Controller_BaseController
{

    public function before()
    {
        parent::before(); // TODO: Change the autogenerated stub
    }

    /**
     * 获取商品类目
     */
    public function get_index()
    {

    }

    /**
     * 获取某类目的子类目
     */
    public function get_child(){

    }

    /**
     * 获取某一个商品类目
     */
    public function get_item()
    {

    }

    /**
     * 创建一个商品类目
     */
    public function post_index()
    {

    }

    /**
     * 修改一个商品类目
     */
    public function put_index()
    {

    }

    /**
     * 更新一个商品类目的某些属性
     */
    public function patch_index()
    {
    }

    /**
     * 删除一个类目
     */
    public function delete_index()
    {

    }

}