<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/2/20 0020
 * Time: 14:22
 */

namespace mall;


class Controller_Deal extends Controller_BaseController
{

    public function before()
    {
        parent::before(); // TODO: Change the autogenerated stub
    }

    /**
     * 取消交易
     *
     * @param bool $wechat
     */
    public function post_cancel()
    {
    }

    /**
     * 获取我的订单
     */
    public function get_list()
    {
    }

    /**
     * 获取某一订单详情
     */
    public function get_item()
    {

    }

    /**
     * 创建一笔交易
     */
    public function post_index()
    {

    }

    /**
     * 修改一笔交易
     */
    public function put_index()
    {

    }

    /**
     * 更新某一笔交易的某些属性
     */
    public function patch_index()
    {
    }

    /**
     * 删除一笔交易
     */
    public function delete_index()
    {

    }

    /**
     * 支付某一笔订单
     */
    public function post_defrayal()
    {

    }

}